obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/

obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/

obj-$(CONFIG_ARCH_MSM)		+= qcom/
obj-$(CONFIG_BATTERY_CW2015)	+= cw2015_battery.o ### add for c3

